### ISSUE TITLE
error while tickets searching in android api level 21

### ISSUE THREAD

**Issue by abanob-atef-roshdy** [travelpayouts/travel-app-android#38] opened 2019-11-03 23:15 UTC
I have an error that is triggered when i launch the android app on api level 21 device but this doesn't happen on android api level 28
i think it is related to kotlin
**here is the error of android studio logs**

> E/AndroidRuntime: FATAL EXCEPTION: main
>                   Process: com.travelpayouts.travel.app, PID: 12427
>                   java.lang.NoSuchMethodError: No static method hashCode(I)I in class Ljava/lang/Integer; or its super classes (declaration of 'java.lang.Integer' appears in /system/framework/core-libart.jar)
>                       at ru.aviasales.api.min_prices.object.PriceCalendarRequestParams.hashCode(PriceCalendarRequestParams.kt)
>                       at java.util.Collections.secondaryHash(Collections.java:3405)
>                       at java.util.HashMap.get(HashMap.java:300)
>                       at ru.aviasales.repositories.pricecalendar.PriceCalendarRepository$RequestCache.get(PriceCalendarRepository.kt:90)
>                       at ru.aviasales.repositories.pricecalendar.PriceCalendarRepository$RequestCache.get(PriceCalendarRepository.kt:90)
>                       at ru.aviasales.repositories.pricecalendar.PriceCalendarRepository.getCachedPriceCalendarData(PriceCalendarRepository.kt:59)
>                       at ru.aviasales.repositories.pricecalendar.PriceCalendarLoader.getLoadedData(PriceCalendarLoader.kt:43)
>                       at ru.aviasales.screen.results.viewmodel.ResultsViewModelBuilder.<init>(ResultsViewModelBuilder.kt:75)
>                       at ru.aviasales.screen.results.dependencies.DaggerResultsComponent.getResultsViewModelBuilder(DaggerResultsComponent.java:47)
>                       at ru.aviasales.screen.results.dependencies.DaggerResultsComponent.getResultsInteractor(DaggerResultsComponent.java:50)
>                       at ru.aviasales.screen.results.dependencies.DaggerResultsComponent.getResultsPresenter(DaggerResultsComponent.java:84)
>                       at ru.aviasales.screen.results.ResultsFragment.onCreate(ResultsFragment.kt:99)
>                       at androidx.fragment.app.Fragment.performCreate(Fragment.java:2414)
>                       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
>                       at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1195)
>                       at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1078)
>                       at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:117)
>                       at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2408)
>                       at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
>                       at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
>                       at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
>                       at android.os.Handler.handleCallback(Handler.java:739)
>                       at android.os.Handler.dispatchMessage(Handler.java:95)
>                       at android.os.Looper.loop(Looper.java:145)
>                       at android.app.ActivityThread.main(ActivityThread.java:7007)
>                       at java.lang.reflect.Method.invoke(Native Method)
>                       at java.lang.reflect.Method.invoke(Method.java:372)
>                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
>                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
> 
i'm hopefully waiting for your reply
Thanks in advance

**Comment by abanob-atef-roshdy** [comment] 2019-11-04 16:22
@b1uebyte please help me since this error makes me a step faraway from ending the app
so please give me a bit quick reply 
Thanks

**Comment by b1uebyte** [comment] 2019-11-05 16:03
@abanob-atef-roshdy I can't reproduce it. Did you change anything in gradle files? Similar bug was fixed in android gradle plugin v 3.4. And default for the project is 3.5.0 (You can try to update it to 3.5.1 just to be sure). Which version of Android Studio do you use?

**Comment by abanob-atef-roshdy** [comment] 2019-11-05 17:37
@b1uebyte Thanks for your useful reply i updated Android studio to the latest version and it works like a charm
Thank you

**Comment by abanob-atef-roshdy** [comment] 2019-11-05 17:42
@b1uebyte I have a question before publishing
I initialized google map successfully and it works well but my google cloud platform account is not paid and google map became limited since 2018 so will that affect my app when published to users
Thanks in advance

**Comment by abanob-atef-roshdy** [comment] 2019-11-07 15:57
@b1uebyte please give me a reply in order to be able to publish my app
Thanks

**Comment by b1uebyte** [comment] 2019-11-18 14:32
Using maps for mobile is free.

**Closed by b1uebyte** 2019-11-18 14:32 UTC
